=== Juanmijr/ApuntesPROYECTOS/Lenguaje de marcas/src/Ejercicios/Examen12018.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT playas (playa+, socorrista*, zona*, trabajo*, vigilante?)>
<!ELEMENT playa (calidadsocorrismo, banderaazul?)>
<!ELEMENT calidadsocorrismo (#PCDATA | numerovisitantes)*>
<!ELEMENT banderaazul (activa? | pasiva?)>
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ENTITY calidad "pero mejorable">
<!ATTLIST playa %atributoNombre;
				tipoembarcacion (altamar | bajamar) #IMPLIED 
				coloragua CDATA #FIXED "azul">
<!ELEMENT numerovisitantes EMPTY>
<!ATTLIST numerovisitantes numero CDATA #REQUIRED>
<!ELEMENT socorrista EMPTY>
<!ATTLIST socorrista nombre ID #REQUIRED>
<!ELEMENT zona (#PCDATA)>
<!ATTLIST zona zonasocorrista IDREF #REQUIRED>
<!ELEMENT trabajo EMPTY>
<!ATTLIST trabajo tipotrabajo IDREFS #REQUIRED>
<!ELEMENT vigiliante EMPTY>
<!ATTLIST vigilante %atributoNombre;
					pistola ( si | no) #IMPLIED
					tipoplaca CDATA #FIXED "autorizado">

=== Juanmijr/ApuntesPROYECTOS/Lenguaje de marcas/src/Ejercicios/Examen12018.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE playas SYSTEM "Examen12018.dtd">
<playas>
	<playa nombre="Benalm치dena" tipoembarcacion="altamar" coloragua="azul">
		<calidadsocorrismo>Excelente
			<numerovisitantes numero="100000"/>
		</calidadsocorrismo>
		<banderaazul>
			<activa></activa>
		</banderaazul>
	</playa>
	<playa nombre="Malapesquera" tipoembarcacion="bajamar">
		<calidadsocorrismo>Buena, &calidad;
			<numerovisitantes numero="50000"/>
		</calidadsocorrismo>	
	</playa>
	<socorrista nombre="Ram칩n"/>
	<socorrista nombre="Ana"/>
	<zona zonasocorrista="Ram칩n">Oeste</zona>
	<trabajo tipotrabajo="Ram칩n Ana"/>
	<vigilante nombre="Juan Miguel" pistola="si" tipoplaca= "autorizado"/>
</playas>
