=== Juanmijr/ApuntesPROYECTOS/Lenguaje de marcas/src/Ejercicios/examen.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (departamento? | asignatura+ | directiva?)*>
<!ENTITY % atributonombre "nombre CDATA #REQUIRED>
<!ENTITY si "SÃ­">
<!ATTLIST profesor %atributonombre; 
			apellido NMTOKEN #REQUIRED
			lugar de nacimiento ID #IMPLIED>
<!ELEMENT departamento EMPTY>
<!ATTLIST departamento rama IDREFS #REQUIRED>
<!ELEMENT asignatura (clase, horasimpartidas?)>
<!ATTLIST asignatura  %atributonombre>
<!ELEMENT clase (numerodealumnos?)>
<!ELEMENT numerodealumnos #PCDATA>
<!ELEMENT horasimpartidas EMPTY>
<!ATTLIST horasimpartidas horas semanales CDATA #IMPLIED>

=== Juanmijr/ApuntesPROYECTOS/Lenguaje de marcas/src/Ejercicios/Examen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profesores SYSTEM "examen.dtd">
<profesores>
	<profesor nombre= "Rafael" apellido= "Muñoz" Lugar de nacimiento= "Lucena">
		<departamento rama= "Informática"/>
		<asignatura nombre= "Programación"/>
			<clase nombre= "1 DAW"
				<numerodealumnos>30</numerodealumnos>
			</clase>
			<horasimpartidas horas semanales= "8"/>
		</asignatura>
		<asignatura nombre= "Lenguaje de Marcas">
			<clase nombre= "1 DAW"
			</clase>
			<horasimpartidas horas semanales="4"
		</asignatura>
		<directiva>Sí</directiva>
	</profesor>
	
</profesores>
