=== Juanmijr/ApuntesPROYECTOS/Lenguaje de marcas/src/Ejercicios/SIMULACROEXAMEN.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY numero "numero 1">
<!ENTITY jugador% caracteristicas "numero CDATA #FIXED "numero 1" 
									posicion (defensa | atacante) "atacante"
									nombre IDREFS #REQUIRED 
									nivel CDATA #REQUIRED 
									potencial CDATA #IMPLIED 
									codigo ID #REQUIRED ">
<!ELEMENT videojuegos (videojuego)>
<!ELEMENT videojuego (FIFA)>
<!ELEMENT FIFA (jugador*|portero*|entrenador*)*>
<!ELEMENT jugador EMPTY>
<!ELEMENT portero EMPTY>
<!ELEMENT entrenador ANY>
<!ATTLIST jugador %caracteristicas;>
<!ATTLIST portero %caracteristicas;>
]>

=== Juanmijr/ApuntesPROYECTOS/Lenguaje de marcas/src/Ejercicios/SIMULACROEXAMEN.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videojuegos SYSTEM "SIMULACROEXAMEN.dtd">
<videojuegos>
	<videojuego>
		<FIFA>
			<jugador numero= "&numero"  nombre="Lionel Messi" nivel="101" codigo="A3"/>
			<jugador nombre="Cristiano Ronaldo" posicion="Extremo" nivel="99" potencial="103"/>
			<jugador nombre="Kyliam MbappÃ©" nivel="85" posicion="Delantero" potencial="150" codigo="A2"/>
			<portero numero= "&numero" nombre="Thibaut Courtois" nivel="92" potencial="100"/>
			<entrenador>Cholo Simeone</entrenador>
		</FIFA>
	</videojuego>
</videojuegos>
